# Generated by Django 4.2.21 on 2025-10-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('news', 'Новости'), ('technology', 'Технологии'), ('science', 'Наука'), ('art', 'Искусство'), ('other', 'Другое')], default='news', max_length=20, verbose_name='Категория'),
        ),
    ]
